# TAILWIND BUILD
[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
  "-c",
  "echo '\nBUILDING TAILWIND...' && npx tailwindcss -i style/tailwind.css -o style/style.css --minify && echo '\nBUILDING TAILWIND DONE\n'",
]
