# TAILWIND BUILD
[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
  "-c",
  "echo '\nBUILDING TAILWIND...' && tailwindcss -i style/tailwind.css -o style/style.css && echo '\nBUILDING TAILWIND DONE\n'",
]
